### ISSUE TITLE
Incomplete compression

### ISSUE THREAD

**Issue by drdevelop** [ZJONSSON/node-unzipper#79] opened 2018-09-20 03:55 UTC
Compression two times must be compressed once.

**Comment by ZJONSSON** [comment] 2018-09-20 19:30
Can you please explain in more detail what the issue is?

**Comment by ZJONSSON** [comment] 2019-05-22 16:07
I hope this has been resolved with #123.  Please reopen if issue persists

**Closed by ZJONSSON** 2019-05-22 16:07 UTC
